Add support for sf ^6.0
1up-lab/OneupFlysystemBundle pull request #257
Opened 2021-12-07 14:25 UTC by odolbeau

This PR:
* Add support for symfony ^6.0
* Remove support for symfony >5.0 & <5.3
* Remove PHPStan & php-cs-fixer from dev dependencies (it uses `jakzal/phpqa` docker image instead)
* Add a Makefile in order to quickly run CS / tests.

Last 2 points can be reverted if needed.

Fix #256

2021-12-07 14:31 UTC, odolbeau commented
If (as I am), you're bored of approving workflows run, I just found this can be configured [here](https://github.com/organizations/1up-lab/settings/actions) as explained [in the documentation](https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#configuring-required-approval-for-workflows-from-public-forks)! :partying_face:

2021-12-07 15:24 UTC, metfan commented on .github/workflows/ci.yml
> +                symfony: [4.4, 5.3, 6.0]
Why not using sf 5.4 instead of 5.3 ?

2021-12-07 15:24 UTC, bytehead commented on .github/workflows/ci.yml
> +                symfony: [4.4, 5.3, 6.0]
I would also go for 5.4 👍

2021-12-09 14:09 UTC, elkuku commented
Please merge :wink:

2021-12-10 15:28 UTC, bytehead requested changes
Thank you very much @odolbeau 🙏 

Would you mind to make a seperate PR for your last 2 points? 

> - Remove PHPStan & php-cs-fixer from dev dependencies (it uses jakzal/phpqa docker image instead)
> - Add a Makefile in order to quickly run CS / tests.

2021-12-11 05:44 UTC, ltlsquare commented
Looks good guys, is there anything else that needs to be done? can help out to get this over the line?

2021-12-13 10:01 UTC, odolbeau commented
There is some permission errors with PHP 8 but I cannot reproduce the bug on my laptop.
@meyerbaptiste, it looks like its linked to the visibility config you added in 4.2.0, could you please take a look? :pray:

2021-12-13 22:57 UTC, meyerbaptiste commented
@odolbeau, I just sent you a PR!

2021-12-14 08:45 UTC, odolbeau commented
> @odolbeau, I just sent you a PR!

@meyerbaptiste do you have a link please? I don't know what you're talking about... :thinking:

2021-12-14 08:47 UTC, bytehead commented
@odolbeau https://github.com/odolbeau/OneupFlysystemBundle/pull/1 🙃

2021-12-14 09:06 UTC, odolbeau commented
Thanks! I didn't get notified, that's strange!
Anyway, thanks a lot @meyerbaptiste, it looks like CI is happy! :ok_hand:

2021-12-14 09:12 UTC, bytehead reviewed
As we test `4.4`, `5.4` and `6.0` in the CI, would it make sense to raise the requirements for `symfony/*` to `"^4.4|^5.4|^6.0"`? ~~The code from [`a62933e` (#257)](https://github.com/1up-lab/OneupFlysystemBundle/pull/257/commits/a62933e188ef0f7d6043a9d5f6fd3c2c3d19984d) is maybe obsolete then?~~ Is not, as we cover `4.4` as well.

2021-12-14 09:14 UTC, odolbeau commented
I did not removed support for sf 5.3 as this version is stille maintained for now https://symfony.com/releases

2021-12-14 09:37 UTC, bytehead approved these changes

2021-12-14 09:38 UTC, merged

2021-12-14 09:38 UTC, bytehead commented
Thank you @odolbeau & @meyerbaptiste ❤️

2021-12-14 09:41 UTC, bytehead commented
I've released [4.3.0](https://github.com/1up-lab/OneupFlysystemBundle/releases/tag/4.3.0)