allow compatibility with flysystem 3
1up-lab/OneupFlysystemBundle pull request #259
Opened 2022-01-17 22:42 UTC by mihaileu

#258 this should allow compatibility with the new flysystem 

with the hope that https://github.com/RoyVoetman/flysystem-gitlab-storage/pull/15 will be merged with 3 as major tag.

2022-01-27 13:32 UTC, RoyVoetman commented
https://github.com/RoyVoetman/flysystem-gitlab-storage/releases/tag/v3.0.0

2022-01-27 13:33 UTC, mihaileu commented
@bytehead I think we can merge this

2022-02-23 15:41 UTC, mihaileu commented
@bytehead  @sheeep !up

2022-02-23 15:41 UTC, bytehead commented on .github/workflows/ci.yml
> -                  php-version: 7.4
As we are still compatible with 7.4, why do you remove the tests on 7.4?

2022-02-23 16:49 UTC, mihaileu commented on .github/workflows/ci.yml
> -                  php-version: 7.4
initially I removed the compatibility with 7.4. I added back, please check if all ok

2022-02-28 17:50 UTC, bytehead requested changes

2022-02-28 17:50 UTC, bytehead commented on .github/workflows/ci.yml
> -                  php-version: 7.4
I would prefer to go on 7.4 as well while checking out the lowest possible dependencies.

2022-03-01 10:28 UTC, bytehead approved these changes

2022-03-01 10:29 UTC, bytehead commented
Thank you!

2022-03-01 10:29 UTC, merged

2022-03-01 10:33 UTC, bytehead commented
[4.4.0](https://github.com/1up-lab/OneupFlysystemBundle/releases/tag/4.4.0) is released - thank you again 🙏